version: "3"
services:
  pg17:
    image: postgres:17
    container_name: postgres17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
    ports:
      - 5433:5432
    volumes:
      - ./db:/var/lib/postgresql/data
