version: "3.4"
services:
  baserow:
    container_name: baserow
    image: baserow/baserow:1.34.2
    environment:
      BASEROW_PUBLIC_URL: 'https://baserow-contabo.sao-pio-tech.com'
      EMAIL_SMTP: true
      EMAIL_SMTP_HOST: smtp.gmail.com
      EMAIL_SMTP_PORT: 587
      EMAIL_SMTP_USER: emotton@gmail.com
      EMAIL_SMTP_PASSWORD: <senha de app>
      EMAIL_SMTP_USE_TLS: true
      EMAIL_SMTP_USE_SSL: false
      FROM_EMAIL: 'emotton@gmail.com'
    ports:
      - "8765:80"
      - "2443:443"
    volumes:
      - ./baserow_data:/baserow/data
