version: "3.8"

services:
  minio:
    image: minio/minio:RELEASE.2023-12-23T07-19-11Z
    container_name: minio
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio-data:/data
    command: server --address ":9000" --console-address ":9001" /data

volumes:
  minio-data:
